// <auto-generated />
namespace ZavenDotNetInterview.App.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class jobsvalidation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(jobsvalidation));
        
        string IMigrationMetadata.Id
        {
            get { return "202004200850359_jobs-validation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
