// <auto-generated />
namespace ZavenDotNetInterview.App.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class jobsupdates : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(jobsupdates));
        
        string IMigrationMetadata.Id
        {
            get { return "202004200033368_jobs-updates"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
